-- EchoNotes — Go Orchestrator SQL queries
-- Source of truth for sqlc generation (sqlc.yaml).
-- The hand-written queries.go implements these exactly.

-- name: CreateJob :one
INSERT INTO jobs.transcription_jobs (sheet_id, user_id, audio_path, instrument)
VALUES ($1, $2, $3, $4)
RETURNING id, sheet_id, user_id, audio_path, instrument, status,
          error_code, error_msg, started_at, finished_at, created_at;

-- name: GetJob :one
SELECT id, sheet_id, user_id, audio_path, instrument, status,
       error_code, error_msg, started_at, finished_at, created_at
FROM jobs.transcription_jobs
WHERE id = $1;

-- name: UpdateJobProcessing :exec
UPDATE jobs.transcription_jobs
SET status = 'processing', started_at = now()
WHERE id = $1;

-- name: UpdateJobDone :exec
UPDATE jobs.transcription_jobs
SET status = 'done', finished_at = now()
WHERE id = $1;

-- name: UpdateJobFailed :exec
UPDATE jobs.transcription_jobs
SET status = 'failed', error_code = $2, error_msg = $3, finished_at = now()
WHERE id = $1;

-- name: ListStalledJobs :many
SELECT id, sheet_id, user_id, audio_path, instrument, status,
       error_code, error_msg, started_at, finished_at, created_at
FROM jobs.transcription_jobs
WHERE status IN ('queued', 'processing')
ORDER BY created_at ASC;

-- name: InsertJobEvent :one
INSERT INTO jobs.job_events (job_id, stage, pct, message)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, stage, pct, message, created_at;

-- name: ListJobEvents :many
SELECT id, job_id, stage, pct, message, created_at
FROM jobs.job_events
WHERE job_id = $1
ORDER BY id ASC;

-- CreateTranscription inserts with a caller-supplied UUID (pre-generated by the worker)
-- so that the artifact directory path matches the stored transcription_id in sheets.sheets.
-- name: CreateTranscription :one
INSERT INTO transcriptions.transcriptions (
  id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
  key_signature, time_signature, tempo_bpm, duration_seconds, model_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
          key_signature, time_signature, tempo_bpm, duration_seconds,
          model_version, created_at;

-- name: GetTranscriptionByJob :one
SELECT id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
       key_signature, time_signature, tempo_bpm, duration_seconds,
       model_version, created_at
FROM transcriptions.transcriptions
WHERE job_id = $1;

-- name: GetTranscriptionByID :one
SELECT id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
       key_signature, time_signature, tempo_bpm, duration_seconds,
       model_version, created_at
FROM transcriptions.transcriptions
WHERE id = $1;

-- UpdateSheetStatus updates the status and transcription_id of a sheet.
-- This crosses the schema boundary (sheets.sheets is TS-owned) as a deliberate
-- design choice: the Go orchestrator is the only service that knows when a
-- transcription is complete, so it updates the sheet status directly.
-- name: UpdateSheetStatus :exec
UPDATE sheets.sheets
SET status = $2, transcription_id = $3
WHERE id = $1;
