package db

import (
	"context"
)

const createJobSQL = `
INSERT INTO jobs.transcription_jobs (sheet_id, user_id, audio_path, instrument)
VALUES ($1, $2, $3, $4)
RETURNING id, sheet_id, user_id, audio_path, instrument, status, error_code, error_msg, started_at, finished_at, created_at
`

func (q *Queries) CreateJob(ctx context.Context, sheetID, userID, audioPath, instrument string) (TranscriptionJob, error) {
	row := q.db.QueryRow(ctx, createJobSQL, sheetID, userID, audioPath, instrument)
	var j TranscriptionJob
	err := row.Scan(&j.ID, &j.SheetID, &j.UserID, &j.AudioPath, &j.Instrument, &j.Status, &j.ErrorCode, &j.ErrorMsg, &j.StartedAt, &j.FinishedAt, &j.CreatedAt)
	return j, err
}

const getJobSQL = `
SELECT id, sheet_id, user_id, audio_path, instrument, status, error_code, error_msg, started_at, finished_at, created_at
FROM jobs.transcription_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (TranscriptionJob, error) {
	row := q.db.QueryRow(ctx, getJobSQL, id)
	var j TranscriptionJob
	err := row.Scan(&j.ID, &j.SheetID, &j.UserID, &j.AudioPath, &j.Instrument, &j.Status, &j.ErrorCode, &j.ErrorMsg, &j.StartedAt, &j.FinishedAt, &j.CreatedAt)
	return j, err
}

const updateJobProcessingSQL = `
UPDATE jobs.transcription_jobs SET status = 'processing', started_at = now() WHERE id = $1
`

func (q *Queries) UpdateJobProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateJobProcessingSQL, id)
	return err
}

const updateJobDoneSQL = `
UPDATE jobs.transcription_jobs SET status = 'done', finished_at = now() WHERE id = $1
`

func (q *Queries) UpdateJobDone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateJobDoneSQL, id)
	return err
}

const updateJobFailedSQL = `
UPDATE jobs.transcription_jobs SET status = 'failed', error_code = $2, error_msg = $3, finished_at = now() WHERE id = $1
`

func (q *Queries) UpdateJobFailed(ctx context.Context, id, errorCode, errorMsg string) error {
	_, err := q.db.Exec(ctx, updateJobFailedSQL, id, errorCode, errorMsg)
	return err
}

const listStalledJobsSQL = `
SELECT id, sheet_id, user_id, audio_path, instrument, status, error_code, error_msg, started_at, finished_at, created_at
FROM jobs.transcription_jobs
WHERE status IN ('queued', 'processing')
ORDER BY created_at ASC
`

func (q *Queries) ListStalledJobs(ctx context.Context) ([]TranscriptionJob, error) {
	rows, err := q.db.Query(ctx, listStalledJobsSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var jobs []TranscriptionJob
	for rows.Next() {
		var j TranscriptionJob
		if err := rows.Scan(&j.ID, &j.SheetID, &j.UserID, &j.AudioPath, &j.Instrument, &j.Status, &j.ErrorCode, &j.ErrorMsg, &j.StartedAt, &j.FinishedAt, &j.CreatedAt); err != nil {
			return nil, err
		}
		jobs = append(jobs, j)
	}
	if jobs == nil {
		jobs = []TranscriptionJob{}
	}
	return jobs, rows.Err()
}

const insertJobEventSQL = `
INSERT INTO jobs.job_events (job_id, stage, pct, message)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, stage, pct, message, created_at
`

func (q *Queries) InsertJobEvent(ctx context.Context, jobID, stage string, pct int16, message *string) (JobEvent, error) {
	row := q.db.QueryRow(ctx, insertJobEventSQL, jobID, stage, pct, message)
	var e JobEvent
	err := row.Scan(&e.ID, &e.JobID, &e.Stage, &e.Pct, &e.Message, &e.CreatedAt)
	return e, err
}

const listJobEventsSQL = `
SELECT id, job_id, stage, pct, message, created_at
FROM jobs.job_events
WHERE job_id = $1
ORDER BY id ASC
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID string) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsSQL, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var events []JobEvent
	for rows.Next() {
		var e JobEvent
		if err := rows.Scan(&e.ID, &e.JobID, &e.Stage, &e.Pct, &e.Message, &e.CreatedAt); err != nil {
			return nil, err
		}
		events = append(events, e)
	}
	if events == nil {
		events = []JobEvent{}
	}
	return events, rows.Err()
}

// CreateTranscriptionParams holds fields for inserting a transcription record.
// ID is pre-generated by the caller so that the artifact directory name matches
// the transcription UUID stored in the sheets table (transcription_id column).
type CreateTranscriptionParams struct {
	ID              string
	JobID           string
	MusicxmlPath    string
	SvgPath         string
	PdfPath         string
	MidiPath        string
	KeySignature    *string
	TimeSignature   *string
	TempoBpm        *float64
	DurationSeconds *float64
	ModelVersion    string
}

const createTranscriptionSQL = `
INSERT INTO transcriptions.transcriptions (
  id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
  key_signature, time_signature, tempo_bpm, duration_seconds, model_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
  key_signature, time_signature, tempo_bpm, duration_seconds, model_version, created_at
`

func (q *Queries) CreateTranscription(ctx context.Context, params CreateTranscriptionParams) (Transcription, error) {
	row := q.db.QueryRow(ctx, createTranscriptionSQL,
		params.ID, params.JobID, params.MusicxmlPath, params.SvgPath, params.PdfPath, params.MidiPath,
		params.KeySignature, params.TimeSignature, params.TempoBpm, params.DurationSeconds, params.ModelVersion,
	)
	var t Transcription
	err := row.Scan(&t.ID, &t.JobID, &t.MusicxmlPath, &t.SvgPath, &t.PdfPath, &t.MidiPath,
		&t.KeySignature, &t.TimeSignature, &t.TempoBpm, &t.DurationSeconds, &t.ModelVersion, &t.CreatedAt)
	return t, err
}

const getTranscriptionByJobSQL = `
SELECT id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
  key_signature, time_signature, tempo_bpm, duration_seconds, model_version, created_at
FROM transcriptions.transcriptions WHERE job_id = $1
`

func (q *Queries) GetTranscriptionByJob(ctx context.Context, jobID string) (Transcription, error) {
	row := q.db.QueryRow(ctx, getTranscriptionByJobSQL, jobID)
	var t Transcription
	err := row.Scan(&t.ID, &t.JobID, &t.MusicxmlPath, &t.SvgPath, &t.PdfPath, &t.MidiPath,
		&t.KeySignature, &t.TimeSignature, &t.TempoBpm, &t.DurationSeconds, &t.ModelVersion, &t.CreatedAt)
	return t, err
}

const getTranscriptionByIDSQL = `
SELECT id, job_id, musicxml_path, svg_path, pdf_path, midi_path,
  key_signature, time_signature, tempo_bpm, duration_seconds, model_version, created_at
FROM transcriptions.transcriptions WHERE id = $1
`

func (q *Queries) GetTranscriptionByID(ctx context.Context, id string) (Transcription, error) {
	row := q.db.QueryRow(ctx, getTranscriptionByIDSQL, id)
	var t Transcription
	err := row.Scan(&t.ID, &t.JobID, &t.MusicxmlPath, &t.SvgPath, &t.PdfPath, &t.MidiPath,
		&t.KeySignature, &t.TimeSignature, &t.TempoBpm, &t.DurationSeconds, &t.ModelVersion, &t.CreatedAt)
	return t, err
}

const updateSheetStatusSQL = `
UPDATE sheets.sheets SET status = $2, transcription_id = $3 WHERE id = $1
`

func (q *Queries) UpdateSheetStatus(ctx context.Context, sheetID, status string, transcriptionID *string) error {
	_, err := q.db.Exec(ctx, updateSheetStatusSQL, sheetID, status, transcriptionID)
	return err
}
